#!/usr/bin/env bash
# kmp-skills installer for Mac/Linux

set -e

COMMAND="${1:-install}"
TARGET="${2:-antigravity}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILLS_ROOT="$REPO_ROOT/skills"
VERSION_FILE="$REPO_ROOT/VERSION"
MANIFEST_FILE=".kmp-skills.json"

AGY_DIR="$HOME/.gemini/config/skills"
CLAUDE_FILE="$HOME/.claude/CLAUDE.md"

# Colors
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
GRAY='\033[1;30m'
NC='\033[0m'

VERSION="?"
if [ -f "$VERSION_FILE" ]; then
    VERSION=$(cat "$VERSION_FILE" | tr -d '[:space:]')
fi

echo ""
echo -e "  ${CYAN}kmp-skills v$VERSION  |  $COMMAND  ->  $TARGET${NC}"
echo -e "  ${GRAY}$(date '+%Y-%m-%d %H:%M')${NC}"
echo ""

print_section() { echo -e "  ${CYAN}[$1]${NC}"; }
print_ok()      { echo -e "  ${GREEN}OK${NC}  $1"; }
print_warn()    { echo -e "  ${YELLOW}!!${NC}  $1"; }
print_err()     { echo -e "  ${RED}XX${NC}  $1"; }
print_step()    { echo -e "  >>  $1"; }

get_all_skills() {
    find "$SKILLS_ROOT" -name "SKILL.md" | grep -v "_template"
}

get_skill_name() {
    grep -m 1 "^name:" "$1" | sed 's/^name:[[:space:]]*//' | tr -d '\r'
}

get_skill_desc() {
    # Simple extraction for single-line descriptions
    grep -m 1 "^description:" "$1" | sed 's/^description:[[:space:]]*//' | tr -d '\r' | sed 's/^> *//'
}

install_agy() {
    print_section "Antigravity + Gemini CLI  ->  $AGY_DIR"
    mkdir -p "$AGY_DIR"
    
    for skill_file in $(get_all_skills); do
        skill_name=$(get_skill_name "$skill_file")
        skill_dir=$(dirname "$skill_file")
        dest_link="$AGY_DIR/$skill_name"
        
        if [ -L "$dest_link" ]; then
            current_target=$(readlink "$dest_link")
            if [ "$current_target" = "$skill_dir" ]; then
                print_ok "$skill_name  (symlink up to date)"
                continue
            else
                rm -f "$dest_link"
            fi
        elif [ -d "$dest_link" ]; then
            print_step "Removing existing directory $skill_name"
            rm -rf "$dest_link"
        fi
        
        print_step "Linking $skill_name"
        ln -s "$skill_dir" "$dest_link"
        print_ok "$skill_name  (symlink created)"
    done
}

status_agy() {
    print_section "Status: Antigravity  ->  $AGY_DIR"
    if [ ! -d "$AGY_DIR" ]; then
        print_warn "Not installed. Run: kmp-skills install"
        return
    fi
    
    for skill_file in $(get_all_skills); do
        skill_name=$(get_skill_name "$skill_file")
        dest_link="$AGY_DIR/$skill_name"
        if [ -L "$dest_link" ]; then
            print_ok "$skill_name  [symlink -> live]"
        else
            print_err "$skill_name  [MISSING -- run update]"
        fi
    done
}

install_claude() {
    print_section "Claude Code CLI  ->  $CLAUDE_FILE"
    mkdir -p "$(dirname "$CLAUDE_FILE")"
    
    BLOCK_START="<!-- kmp-skills:start -->"
    BLOCK_END="<!-- kmp-skills:end -->"
    
    # Create temporary file with new block
    TMP_BLOCK=$(mktemp)
    echo "$BLOCK_START" > "$TMP_BLOCK"
    echo "<!-- Generated by kmp-skills v$VERSION. Do not edit this block. -->" >> "$TMP_BLOCK"
    echo "" >> "$TMP_BLOCK"
    echo "# KMP Development Skills (kmp-skills v$VERSION)" >> "$TMP_BLOCK"
    echo "" >> "$TMP_BLOCK"
    
    for skill_file in $(get_all_skills); do
        skill_name=$(get_skill_name "$skill_file")
        echo "---" >> "$TMP_BLOCK"
        echo "" >> "$TMP_BLOCK"
        echo "## Skill: $skill_name" >> "$TMP_BLOCK"
        echo "" >> "$TMP_BLOCK"
        # Strip frontmatter
        awk '/^---$/{ if (!started) {started=1; next} if (!ended) {ended=1; next} } ended{print}' "$skill_file" >> "$TMP_BLOCK"
        echo "" >> "$TMP_BLOCK"
        print_ok "$skill_name added"
    done
    
    echo "$BLOCK_END" >> "$TMP_BLOCK"
    
    if [ -f "$CLAUDE_FILE" ]; then
        if grep -q "$BLOCK_START" "$CLAUDE_FILE"; then
            # Replace existing block using sed
            sed -i.bak -e "/$BLOCK_START/,/$BLOCK_END/c\\" -e "$(cat "$TMP_BLOCK" | sed 's/$/\\/')" "$CLAUDE_FILE"
            # Remove trailing backslash from the last line that sed requires
            sed -i.bak -e 's/\\$//' "$CLAUDE_FILE"
            rm -f "$CLAUDE_FILE.bak"
        else
            echo "" >> "$CLAUDE_FILE"
            cat "$TMP_BLOCK" >> "$CLAUDE_FILE"
        fi
    else
        cat "$TMP_BLOCK" > "$CLAUDE_FILE"
    fi
    rm -f "$TMP_BLOCK"
    print_ok "CLAUDE.md updated -> $CLAUDE_FILE"
}

status_claude() {
    print_section "Status: Claude  ->  $CLAUDE_FILE"
    if [ -f "$CLAUDE_FILE" ] && grep -q "<!-- kmp-skills:start -->" "$CLAUDE_FILE"; then
        print_ok "Installed (kmp-skills block present)"
    else
        print_warn "Not installed or block missing"
    fi
}

cmd_update() {
    print_section "git pull -> $REPO_ROOT"
    cd "$REPO_ROOT"
    if git pull; then
        print_ok "git pull complete"
    else
        print_warn "git pull failed"
    fi
    
    if [[ "$TARGET" == "antigravity" || "$TARGET" == "all" ]]; then install_agy; fi
    if [[ "$TARGET" == "claude" || "$TARGET" == "all" ]];      then install_claude; fi
}

cmd_list() {
    print_section "Skills in this repo"
    for skill_file in $(get_all_skills); do
        name=$(get_skill_name "$skill_file")
        desc=$(get_skill_desc "$skill_file")
        echo -e "    ${CYAN}$name${NC}"
        if [ ! -z "$desc" ]; then
            echo -e "      ${GRAY}${desc:0:90}${NC}"
        fi
    done
}

case "$COMMAND" in
    install)
        if [[ "$TARGET" == "antigravity" || "$TARGET" == "all" ]]; then install_agy; fi
        if [[ "$TARGET" == "claude" || "$TARGET" == "all" ]];      then install_claude; fi
        ;;
    status)
        if [[ "$TARGET" == "antigravity" || "$TARGET" == "all" ]]; then status_agy; fi
        if [[ "$TARGET" == "claude" || "$TARGET" == "all" ]];      then status_claude; fi
        ;;
    update)
        cmd_update
        ;;
    list)
        cmd_list
        ;;
    *)
        print_err "Unknown command: $COMMAND"
        echo "Commands: install, update, status, list"
        exit 1
        ;;
esac

echo ""
echo -e "  ${GREEN}Done.${NC}"
echo ""
